root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/server server.go"
entrypoint = ["./tmp/server", "-config", "config.yaml"]
include_ext = ["go"]
exclude_dir = [
    "tmp",
    "node_modules",
    "web",
]

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
